### ISSUE TITLE
There are new MediaFeedType in PlayOff

### ISSUE THREAD

**Issue by antiden** [kompot/nhl-tv-geeky-streams#66]
Hi,

new ones started showing up MediaFeedType: US NATIONAL and CA NATIONAL.

In default: US NATIONAL

National = "US NATIONAL", in nhlStatsApi.ts

**Comment by rseanhall** [comment]
I'm confused why you want to change National to "US NATIONAL". Won't some people want "CA NATIONAL"? It's been a while since I've been in the code, I thought this was mostly just for helping to know which feed to pick. If this is breaking some functionality for you then it would help to explain what broke.

**Comment by antiden** [comment]
Everything works fine, there are no problems, only when you make a -passive method, it does not start because it cannot find the source.

**Comment by rseanhall** [comment]
I pushed a [change](https://github.com/kompot/nhl-tv-geeky-streams/commit/e2f3ab9f3fe054a2fb44a3d1af97c91a9c3a8e53) that hopefully handles it. Let me know if it doesn't work for you.

![image](https://user-images.githubusercontent.com/7038916/232961013-9e666eae-b9cd-4049-970a-b3fbd6a84450.png)
