### ISSUE TITLE
Showing multiple feeds

### ISSUE THREAD

**Issue by antiden** [kompot/nhl-tv-geeky-streams#68]
@rseanhall 

I use --passive mode and have error for download video, "feed to watch" with 2 NATIONAL options. Screen:
![2023-04-21_02-28-53](https://user-images.githubusercontent.com/6802145/233509384-3b76d58e-d870-4807-8d82-f13e699d20f7.png)

**Comment by rseanhall** [comment]
I have no idea what they're doing. Each feed has a name and description. They are giving conflicting information:

![image](https://user-images.githubusercontent.com/7038916/233523243-a3c06c93-9ff2-433e-8dac-f0e0347fa32f.png)

**Comment by antiden** [comment]
Hah, I agree. Can take the first one from the list, for example, if 2 or more NATIONAL or HOME get first for `--passive` mode, of course use order:

```
Home = "HOME",
Away = "AWAY",
National = "NATIONAL",
```

**Comment by rseanhall** [comment]
There's really two issues here. The first is that `--passive` mode doesn't work when there are multiple preferred feeds. It should prefer the home/away first (depending on whether your team is home or away) like you said. But in this case that wouldn't help since there are two national feeds and no home/away feeds. By design, `--passive` gives up here. I guess I could add an option that says you just want it to pick a feed if there are multiple preferred feeds.

The second issue is how they're creating the feeds in the first round of the playoffs. Theoretically, there should be 4 feeds in games between two American teams. The US National feed, CA National feed, Home regional feed, and Away regional feed. I haven't downloaded them all to see what they're actually providing, but in any case it seems like it needs to provide both the name and description. Given that some feeds have "HOME" as the name and "AWAY" as the description, it might guess wrong about whether it's home or away so you if you actually care which feed you want to watch then you'll probably not be able to use `--passive`. I have been waiting to get more data before deciding how to handle this since they seem to be doing something different every day.

**Comment by antiden** [comment]
ok, undertand. NHL TV is't a gift =)

**Comment by rseanhall** [comment]
I fixed this in https://github.com/kompot/nhl-tv-geeky-streams/commit/20d22f03acd729327c7aa8a357b1aa0209ee3c8d, https://github.com/kompot/nhl-tv-geeky-streams/commit/876ce9ec6836bbef3eca324debc7858533067218, and https://github.com/kompot/nhl-tv-geeky-streams/commit/a3b2177766446aefac3a895a0148784249647734. At least until they break it again :)
