### ISSUE TITLE
Auto streaming to other platforms

### ISSUE THREAD

**Issue by antiden** [kompot/nhl-tv-geeky-streams#69]
Hi,

I have a question, in this scrips, use streamlink or ffmpeg for coding video, where i can change settings for streaming to RTMP server?

Example:
1. Select game and stream
2. Add Streaming code (before, env, config or cli)
3. Use standard settings for streaming: `ffmpeg -re -sseof -5 -i "video/2023-04-23_CAR_at_NYI_(AWAY)_720p_live.mp4" -c:v libx264 -preset veryfast -crf 25 -b:v 2000k -maxrate 2000k -bufsize 4000k -c:a aac -b:a 128k -ar 44100 -f flv -flvflags no_duration_filesize "rtmp://server/<code>"`
4. No need save video, or use download metadata for checking End.

P.S. For example: ffmpeg -i $(streamlink -O <site1_m3u8_url>) -c copy -f flv rtmp://<site2_rtmp_server>/<stream_key>

Thx!

**Comment by rseanhall** [comment]
This program was really designed to download the file which allows you to download the highest quality feed that you want without worrying about it downgrading in the middle because of a bad connection. It also allows you to resume the download if it fails in the middle. I guess there could be a new option that it runs a command after the download starts so you don't have to do that manually but I don't think it's worth it to change this program to stop downloading the file.

**Comment by antiden** [comment]
Yes, agree. Now i have two script, your and for streaming. This is question, only for information. Script working fine. Thx.
