### ISSUE TITLE
Can't download the active video

### ISSUE THREAD

**Issue by antiden** [kompot/nhl-tv-geeky-streams#71]
Hi, 

I can't download the active video from NHL.tv, the error flies out: "NHL.TV Feed access token was not found.", moreover, past games can be downloaded.

**Comment by rseanhall** [comment]
I am seeing the same issue. I can't access any of tonight's feeds but have no problems accessing the games from yesterday. I am able to login and watch tonight's game on their website, though. I'll have to look into it.

**Comment by antiden** [comment]
I think I need to close the issue, since the script itself works, this is the problem of the NHL TV itself, since the video is not available even from the archive

**Comment by rseanhall** [comment]
What do you mean that the video is not available from the archive? I am able to download all of the games from Thursday and Friday. I think we might have to close this issue since there's no way for me test it out anymore. The goal is for this project to work if their website works, so hopefully it was just a glitch on their end. I wasn't able to test the live game yesterday so I don't know whether the live games worked yesterday.
